### ISSUE TITLE
css对连续的字符折行

### ISSUE THREAD

**Issue by mahyuan** [mhy-web/Algorithm_demo#21]
css对连续的字符折行显示时必须先打断，否则会自动查找空格然后进行折行

```css
div {
    white-space: normal;
    word-break: break-all;
}
```
